import { Deck, ScriptureCard } from './types';

function card(id: string, reference: string, hint: string, text: string, deckId: string): ScriptureCard {
  return { id, reference, hint, text, deckId };
}

export const decks: Deck[] = [
  // ── Level 0 (Starter Decks) ──────────────────────────────────────────
  {
    id: 'foundation',
    name: 'Called Before the Foundation of the World',
    description: 'Discover how God chose and called you before time began.',
    icon: '🌍',
    color: '#6366f1',
    unlockLevel: 0,
    cards: [
      card('fd1', 'Ephesians 1:4', 'Chosen before the foundation', 'According as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love:', 'foundation'),
      card('fd2', '2 Timothy 1:9', 'Called before time began', 'Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace, which was given us in Christ Jesus before the world began,', 'foundation'),
      card('fd3', 'Romans 8:29', 'Foreknown and predestined', 'For whom he did foreknow, he also did predestinate to be conformed to the image of his Son, that he might be the firstborn among many brethren.', 'foundation'),
      card('fd4', 'Romans 8:30', 'Predestined and called', 'Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified.', 'foundation'),
      card('fd5', 'Jeremiah 1:5', 'Known before birth', 'Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee, and I ordained thee a prophet unto the nations.', 'foundation'),
      card('fd6', 'Isaiah 49:1', 'Called from the womb', 'The LORD hath called me from the womb; from the bowels of my mother hath he made mention of my name.', 'foundation'),
      card('fd7', 'Isaiah 46:10', 'Purpose established', 'Declaring the end from the beginning, and from ancient times the things that are not yet done, saying, My counsel shall stand, and I will do all my pleasure:', 'foundation'),
      card('fd8', 'Psalm 139:16', 'Days written beforehand', 'Thine eyes did see my substance, yet being unperfect; and in thy book all my members were written, which in continuance were fashioned, when as yet there was none of them.', 'foundation'),
      card('fd9', 'Galatians 1:15', 'Separated from the womb', 'But when it pleased God, who separated me from my mother\'s womb, and called me by his grace,', 'foundation'),
      card('fd10', 'Proverbs 19:21', 'Counsel of the Lord stands', 'There are many devices in a man\'s heart; nevertheless the counsel of the LORD, that shall stand.', 'foundation'),
      card('fd11', 'Ecclesiastes 3:14', 'God\'s work forever', 'I know that, whatsoever God doeth, it shall be for ever: nothing can be put to it, nor any thing taken from it: and God doeth it, that men should fear before him.', 'foundation'),
      card('fd12', 'Acts 15:18', 'Known unto God', 'Known unto God are all his works from the beginning of the world.', 'foundation'),
      card('fd13', 'Isaiah 41:4', 'Called the generations', 'Who hath wrought and done it, calling the generations from the beginning? I the LORD, the first, and with the last; I am he.', 'foundation'),
      card('fd14', 'Isaiah 44:2', 'Formed and chosen', 'Thus saith the LORD that made thee, and formed thee from the womb, which will help thee; Fear not, O Jacob, my servant; and thou, Jesurun, whom I have chosen.', 'foundation'),
      card('fd15', 'Psalm 33:11', 'Counsel forever', 'The counsel of the LORD standeth for ever, the thoughts of his heart to all generations.', 'foundation'),
      card('fd16', 'Romans 9:11', 'Purpose before works', '(For the children being not yet born, neither having done any good or evil, that the purpose of God according to election might stand, not of works, but of him that calleth;)', 'foundation'),
      card('fd17', 'Isaiah 14:24', 'Purpose performed', 'The LORD of hosts hath sworn, saying, Surely as I have thought, so shall it come to pass; and as I have purposed, so shall it stand:', 'foundation'),
      card('fd18', 'Isaiah 55:11', 'God\'s word accomplishes', 'So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.', 'foundation'),
      card('fd19', 'John 15:16', 'Chosen and appointed', 'Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain:', 'foundation'),
      card('fd20', '1 Peter 1:20', 'Foreordained before the world', 'Who verily was foreordained before the foundation of the world, but was manifest in these last times for you,', 'foundation'),
      card('fd21', 'Revelation 13:8', 'From the foundation', 'The Lamb slain from the foundation of the world.', 'foundation'),
    ],
  },
  {
    id: 'salvation',
    name: 'The Salvation That Saves by Grace',
    description: 'Embrace the gift of salvation through God\'s amazing grace.',
    icon: '✝️',
    color: '#8b5cf6',
    unlockLevel: 0,
    cards: [
      card('sv1', 'Ephesians 2:8', 'Saved by grace', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:', 'salvation'),
      card('sv2', 'Ephesians 2:9', 'Not of works', 'Not of works, lest any man should boast.', 'salvation'),
      card('sv3', 'Romans 3:24', 'Justified freely', 'Being justified freely by his grace through the redemption that is in Christ Jesus:', 'salvation'),
      card('sv4', 'Titus 3:5', 'According to mercy', 'Not by works of righteousness which we have done, but according to his mercy he saved us, by the washing of regeneration, and renewing of the Holy Ghost;', 'salvation'),
      card('sv5', 'Romans 5:1', 'Justified by faith', 'Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:', 'salvation'),
      card('sv6', 'Romans 5:2', 'Access by faith', 'By whom also we have access by faith into this grace wherein we stand, and rejoice in hope of the glory of God.', 'salvation'),
      card('sv7', 'Romans 5:8', 'Grace demonstrated', 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.', 'salvation'),
      card('sv8', 'John 1:12', 'Power to become', 'But as many as received him, to them gave he power to become the sons of God, even to them that believe on his name:', 'salvation'),
      card('sv9', 'John 3:16', 'God so loved', 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.', 'salvation'),
      card('sv10', 'Romans 10:9', 'Confess and believe', 'That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.', 'salvation'),
      card('sv11', 'Romans 10:10', 'Belief unto righteousness', 'For with the heart man believeth unto righteousness; and with the mouth confession is made unto salvation.', 'salvation'),
      card('sv12', 'Acts 4:12', 'No other name', 'Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.', 'salvation'),
      card('sv13', '2 Corinthians 5:17', 'New creature', 'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.', 'salvation'),
      card('sv14', 'Romans 6:23', 'Gift of God', 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.', 'salvation'),
      card('sv15', 'Hebrews 7:25', 'Saved to the uttermost', 'Wherefore he is able also to save them to the uttermost that come unto God by him, seeing he ever liveth to make intercession for them.', 'salvation'),
      card('sv16', 'John 5:24', 'Passed from death', 'Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but is passed from death unto life.', 'salvation'),
      card('sv17', 'Colossians 1:13', 'Delivered and translated', 'Who hath delivered us from the power of darkness, and hath translated us into the kingdom of his dear Son:', 'salvation'),
      card('sv18', 'Colossians 1:14', 'Redemption through blood', 'In whom we have redemption through his blood, even the forgiveness of sins:', 'salvation'),
      card('sv19', '1 Peter 1:18', 'Redeemed not with silver', 'Forasmuch as ye know that ye were not redeemed with corruptible things, as silver and gold, from your vain conversation received by tradition from your fathers;', 'salvation'),
      card('sv20', '1 Peter 1:19', 'Precious blood', 'But with the precious blood of Christ, as of a lamb without blemish and without spot:', 'salvation'),
      card('sv21', 'Romans 11:6', 'Grace is no longer works', 'And if by grace, then is it no more of works: otherwise grace is no more grace.', 'salvation'),
    ],
  },

  // ── Level 2 ───────────────────────────────────────────────────────────
  {
    id: 'healing',
    name: 'The Healing Christ in the Book of Luke',
    description: 'Walk through the Gospel of Luke and witness Christ the Healer.',
    icon: '🩹',
    color: '#ec4899',
    unlockLevel: 2,
    cards: [
      card('hl1', 'Luke 4:18', 'Anointed to heal', 'The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the brokenhearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised,', 'healing'),
      card('hl2', 'Luke 4:40', 'Laid hands on every one', 'Now when the sun was setting, all they that had any sick with divers diseases brought them unto him; and he laid his hands on every one of them, and healed them.', 'healing'),
      card('hl3', 'Luke 5:12', 'Lord, if thou wilt', 'And it came to pass, when he was in a certain city, behold a man full of leprosy: who seeing Jesus fell on his face, and besought him, saying, Lord, if thou wilt, thou canst make me clean.', 'healing'),
      card('hl4', 'Luke 5:13', 'I will, be thou clean', 'And he put forth his hand, and touched him, saying, I will: be thou clean. And immediately the leprosy departed from him.', 'healing'),
      card('hl5', 'Luke 5:17', 'Power present to heal', 'And it came to pass on a certain day, as he was teaching, that there were Pharisees and doctors of the law sitting by... and the power of the Lord was present to heal them.', 'healing'),
      card('hl6', 'Luke 5:20', 'Thy sins forgiven', 'And when he saw their faith, he said unto him, Man, thy sins are forgiven thee.', 'healing'),
      card('hl7', 'Luke 5:24', 'Authority to heal', 'But that ye may know that the Son of man hath power upon earth to forgive sins... Arise, and take up thy couch, and go into thine house.', 'healing'),
      card('hl8', 'Luke 6:10', 'Restored hand', 'And looking round about upon them all, he said unto the man, Stretch forth thy hand. And he did so: and his hand was restored whole as the other.', 'healing'),
      card('hl9', 'Luke 6:19', 'Virtue went out', 'And the whole multitude sought to touch him: for there went virtue out of him, and healed them all.', 'healing'),
      card('hl10', 'Luke 7:7', 'Speak the word', 'But say in a word, and my servant shall be healed.', 'healing'),
      card('hl11', 'Luke 7:10', 'Found whole', 'And they that were sent, returning to the house, found the servant whole that had been sick.', 'healing'),
      card('hl12', 'Luke 8:43', 'Issue of blood', 'And a woman having an issue of blood twelve years... could not be healed of any,', 'healing'),
      card('hl13', 'Luke 8:44', 'Immediately stanched', 'Came behind him, and touched the border of his garment: and immediately her issue of blood stanched.', 'healing'),
      card('hl14', 'Luke 8:48', 'Thy faith made thee whole', 'And he said unto her, Daughter, be of good comfort: thy faith hath made thee whole; go in peace.', 'healing'),
      card('hl15', 'Luke 8:50', 'Only believe', 'Fear not: believe only, and she shall be made whole.', 'healing'),
      card('hl16', 'Luke 9:11', 'Healed those in need', 'And he received them, and spake unto them of the kingdom of God, and healed them that had need of healing.', 'healing'),
      card('hl17', 'Luke 13:12', 'Loosed from infirmity', 'And when Jesus saw her, he called her to him, and said unto her, Woman, thou art loosed from thine infirmity.', 'healing'),
      card('hl18', 'Luke 13:13', 'Immediately made straight', 'And he laid his hands on her: and immediately she was made straight, and glorified God.', 'healing'),
      card('hl19', 'Luke 14:4', 'Took and healed', 'And he took him, and healed him, and let him go;', 'healing'),
      card('hl20', 'Luke 17:14', 'As they went, cleansed', 'And when he saw them, he said unto them, Go shew yourselves unto the priests. And it came to pass, that, as they went, they were cleansed.', 'healing'),
      card('hl21', 'Luke 18:42', 'Receive thy sight', 'And Jesus said unto him, Receive thy sight: thy faith hath saved thee.', 'healing'),
    ],
  },
  {
    id: 'love',
    name: 'The Love of God in Me',
    description: 'Experience the transforming love of God dwelling within you.',
    icon: '❤️',
    color: '#f43f5e',
    unlockLevel: 2,
    cards: [
      card('lv1', 'Romans 5:5', 'Love poured out', 'And hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost which is given unto us.', 'love'),
      card('lv2', '1 John 4:9', 'Love manifested', 'In this was manifested the love of God toward us, because that God sent his only begotten Son into the world, that we might live through him.', 'love'),
      card('lv3', '1 John 4:10', 'Love initiated', 'Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins.', 'love'),
      card('lv4', '1 John 4:11', 'Love flows through us', 'Beloved, if God so loved us, we ought also to love one another.', 'love'),
      card('lv5', '1 John 4:12', 'God dwells in us', 'No man hath seen God at any time. If we love one another, God dwelleth in us, and his love is perfected in us.', 'love'),
      card('lv6', '1 John 4:13', 'Abiding through the Spirit', 'Hereby know we that we dwell in him, and he in us, because he hath given us of his Spirit.', 'love'),
      card('lv7', 'John 15:9', 'Abide in my love', 'As the Father hath loved me, so have I loved you: continue ye in my love.', 'love'),
      card('lv8', 'John 15:10', 'Love and obedience', 'If ye keep my commandments, ye shall abide in my love; even as I have kept my Father\'s commandments, and abide in his love.', 'love'),
      card('lv9', 'Colossians 3:14', 'Bond of perfection', 'And above all these things put on charity, which is the bond of perfectness.', 'love'),
      card('lv10', 'Galatians 2:20', 'Christ lives in me', 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.', 'love'),
      card('lv11', 'Galatians 5:22', 'Fruit of the Spirit', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,', 'love'),
      card('lv12', 'Ephesians 3:17', 'Rooted in love', 'That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love,', 'love'),
      card('lv13', 'Ephesians 3:18', 'Dimensions of love', 'May be able to comprehend with all saints what is the breadth, and length, and depth, and height;', 'love'),
      card('lv14', 'Ephesians 3:19', 'Filled with fullness', 'And to know the love of Christ, which passeth knowledge, that ye might be filled with all the fulness of God.', 'love'),
      card('lv15', '2 Corinthians 5:14', 'Love compels', 'For the love of Christ constraineth us; because we thus judge, that if one died for all, then were all dead:', 'love'),
      card('lv16', 'Romans 8:10', 'Christ in you', 'And if Christ be in you, the body is dead because of sin; but the Spirit is life because of righteousness.', 'love'),
      card('lv17', 'Romans 8:35', 'Nothing separates', 'Who shall separate us from the love of Christ? shall tribulation, or distress, or persecution, or famine, or nakedness, or peril, or sword?', 'love'),
      card('lv18', 'Romans 8:39', 'Love secured', 'Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.', 'love'),
      card('lv19', '1 Corinthians 13:13', 'Greatest is love', 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.', 'love'),
      card('lv20', 'John 13:34', 'New commandment', 'A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.', 'love'),
      card('lv21', 'John 13:35', 'Love reveals discipleship', 'By this shall all men know that ye are my disciples, if ye have love one to another.', 'love'),
    ],
  },

  // ── Level 3 ───────────────────────────────────────────────────────────
  {
    id: 'forgiveness',
    name: 'The Power of Forgiveness',
    description: 'Unlock the transforming power of forgiveness in your life.',
    icon: '🕊️',
    color: '#06b6d4',
    unlockLevel: 3,
    cards: [
      card('fg1', 'Matthew 6:12', 'Forgive our debts', 'And forgive us our debts, as we forgive our debtors.', 'forgiveness'),
      card('fg2', 'Matthew 6:14', 'Forgiveness brings forgiveness', 'For if ye forgive men their trespasses, your heavenly Father will also forgive you:', 'forgiveness'),
      card('fg3', 'Matthew 6:15', 'Withholding forgiveness', 'But if ye forgive not men their trespasses, neither will your Father forgive your trespasses.', 'forgiveness'),
      card('fg4', 'Matthew 18:21', 'How often forgive', 'Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times?', 'forgiveness'),
      card('fg5', 'Matthew 18:22', 'Seventy times seven', 'Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven.', 'forgiveness'),
      card('fg6', 'Matthew 18:27', 'Moved with compassion', 'Then the lord of that servant was moved with compassion, and loosed him, and forgave him the debt.', 'forgiveness'),
      card('fg7', 'Matthew 18:32', 'Debt forgiven', 'Then his lord, after that he had called him, said unto him, O thou wicked servant, I forgave thee all that debt, because thou desiredst me:', 'forgiveness'),
      card('fg8', 'Matthew 18:35', 'From the heart', 'So likewise shall my heavenly Father do also unto you, if ye from your hearts forgive not every one his brother their trespasses.', 'forgiveness'),
      card('fg9', 'Luke 6:37', 'Forgive and be forgiven', 'Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:', 'forgiveness'),
      card('fg10', 'Luke 7:47', 'Loved much', 'Wherefore I say unto thee, Her sins, which are many, are forgiven; for she loved much: but to whom little is forgiven, the same loveth little.', 'forgiveness'),
      card('fg11', 'Luke 23:34', 'Forgive them', 'Then said Jesus, Father, forgive them; for they know not what they do. And they parted his raiment, and cast lots.', 'forgiveness'),
      card('fg12', 'Acts 3:19', 'Times of refreshing', 'Repent ye therefore, and be converted, that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord;', 'forgiveness'),
      card('fg13', 'Ephesians 4:32', 'Forgive as God forgave', 'And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ\'s sake hath forgiven you.', 'forgiveness'),
      card('fg14', 'Colossians 3:13', 'Even as Christ forgave', 'Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.', 'forgiveness'),
      card('fg15', 'Psalm 103:12', 'As far as the east', 'As far as the east is from the west, so far hath he removed our transgressions from us.', 'forgiveness'),
      card('fg16', 'Isaiah 1:18', 'Though sins be scarlet', 'Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.', 'forgiveness'),
      card('fg17', 'Micah 7:18', 'Delights in mercy', 'Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy.', 'forgiveness'),
      card('fg18', 'Micah 7:19', 'Cast into the sea', 'He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.', 'forgiveness'),
      card('fg19', 'Hebrews 8:12', 'Remember no more', 'For I will be merciful to their unrighteousness, and their sins and their iniquities will I remember no more.', 'forgiveness'),
      card('fg20', '1 John 1:9', 'Faithful and just', 'If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.', 'forgiveness'),
      card('fg21', 'Romans 4:7', 'Sins covered', 'Saying, Blessed are they whose iniquities are forgiven, and whose sins are covered.', 'forgiveness'),
    ],
  },
  {
    id: 'promise',
    name: 'The Promise of the Father',
    description: 'Receive the promised gift of the Holy Spirit in power.',
    icon: '🔥',
    color: '#f59e0b',
    unlockLevel: 3,
    cards: [
      card('pm1', 'Luke 24:49', 'Promise of the Father', 'And, behold, I send the promise of my Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high.', 'promise'),
      card('pm2', 'Acts 1:4', 'Wait for the promise', 'And, being assembled together with them, commanded them that they should not depart from Jerusalem, but wait for the promise of the Father, which, saith he, ye have heard of me.', 'promise'),
      card('pm3', 'Acts 1:5', 'Baptized with the Holy Ghost', 'For John truly baptized with water; but ye shall be baptized with the Holy Ghost not many days hence.', 'promise'),
      card('pm4', 'Acts 1:8', 'Power to witness', 'But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth.', 'promise'),
      card('pm5', 'Joel 2:28', 'Spirit poured out', 'And it shall come to pass afterward, that I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see visions:', 'promise'),
      card('pm6', 'John 14:16', 'Another Comforter', 'And I will pray the Father, and he shall give you another Comforter, that he may abide with you for ever;', 'promise'),
      card('pm7', 'John 14:17', 'Spirit of truth', 'Even the Spirit of truth; whom the world cannot receive, because it seeth him not, neither knoweth him: but ye know him; for he dwelleth with you, and shall be in you.', 'promise'),
      card('pm8', 'John 14:26', 'Teacher and reminder', 'But the Comforter, which is the Holy Ghost, whom the Father will send in my name, he shall teach you all things, and bring all things to your remembrance, whatsoever I have said unto you.', 'promise'),
      card('pm9', 'John 15:26', 'Testifies of Christ', 'But when the Comforter is come, whom I will send unto you from the Father, even the Spirit of truth, which proceedeth from the Father, he shall testify of me:', 'promise'),
      card('pm10', 'John 16:7', 'Expedient that I go', 'Nevertheless I tell you the truth; It is expedient for you that I go away: for if I go not away, the Comforter will not come unto you; but if I depart, I will send him unto you.', 'promise'),
      card('pm11', 'John 16:13', 'Guides into truth', 'Howbeit when he, the Spirit of truth, is come, he will guide you into all truth: for he shall not speak of himself; but whatsoever he shall hear, that shall he speak: and he will shew you things to come.', 'promise'),
      card('pm12', 'Acts 2:1', 'Day of Pentecost', 'And when the day of Pentecost was fully come, they were all with one accord in one place.', 'promise'),
      card('pm13', 'Acts 2:4', 'Filled with the Spirit', 'And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.', 'promise'),
      card('pm14', 'Acts 2:16', 'Spoken by the prophet', 'But this is that which was spoken by the prophet Joel;', 'promise'),
      card('pm15', 'Acts 2:17', 'Promise fulfilled', 'And it shall come to pass in the last days, saith God, I will pour out of my Spirit upon all flesh: and your sons and your daughters shall prophesy...', 'promise'),
      card('pm16', 'Acts 2:38', 'Gift of the Holy Ghost', 'Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.', 'promise'),
      card('pm17', 'Acts 2:39', 'Promise to all', 'For the promise is unto you, and to your children, and to all that are afar off, even as many as the Lord our God shall call.', 'promise'),
      card('pm18', 'Galatians 3:14', 'Promise through faith', 'That the blessing of Abraham might come on the Gentiles through Jesus Christ; that we might receive the promise of the Spirit through faith.', 'promise'),
      card('pm19', 'Ephesians 1:13', 'Sealed with the Spirit', 'In whom ye also trusted, after that ye heard the word of truth, the gospel of your salvation: in whom also after that ye believed, ye were sealed with that holy Spirit of promise,', 'promise'),
      card('pm20', 'Ephesians 1:14', 'Earnest of inheritance', 'Which is the earnest of our inheritance until the redemption of the purchased possession, unto the praise of his glory.', 'promise'),
      card('pm21', 'Romans 8:11', 'Life-giving Spirit', 'But if the Spirit of him that raised up Jesus from the dead dwell in you, he that raised up Christ from the dead shall also quicken your mortal bodies by his Spirit that dwelleth in you.', 'promise'),
    ],
  },

  // ── Level 5 ───────────────────────────────────────────────────────────
  {
    id: 'evangelist',
    name: 'The Work of an Evangelist',
    description: 'Be equipped and sent to proclaim the good news to the world.',
    icon: '📢',
    color: '#10b981',
    unlockLevel: 5,
    cards: [
      card('ev1', '2 Timothy 4:5', 'Do the work', 'But watch thou in all things, endure afflictions, do the work of an evangelist, make full proof of thy ministry.', 'evangelist'),
      card('ev2', 'Matthew 28:19', 'Go and teach', 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:', 'evangelist'),
      card('ev3', 'Matthew 28:20', 'Teaching obedience', 'Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen.', 'evangelist'),
      card('ev4', 'Mark 16:15', 'Preach the gospel', 'And he said unto them, Go ye into all the world, and preach the gospel to every creature.', 'evangelist'),
      card('ev5', 'Luke 19:10', 'Seek and save', 'For the Son of man is come to seek and to save that which was lost.', 'evangelist'),
      card('ev6', 'Luke 4:18', 'Sent to preach', 'The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor...', 'evangelist'),
      card('ev7', 'Acts 1:8', 'Power to witness', 'But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me...', 'evangelist'),
      card('ev8', 'Romans 1:16', 'Not ashamed', 'For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth...', 'evangelist'),
      card('ev9', 'Romans 10:14', 'How shall they hear', 'How then shall they call on him in whom they have not believed? and how shall they believe in him of whom they have not heard?', 'evangelist'),
      card('ev10', 'Romans 10:15', 'Beautiful feet', 'And how shall they preach, except they be sent? as it is written, How beautiful are the feet of them that preach the gospel of peace...', 'evangelist'),
      card('ev11', '1 Corinthians 1:21', 'By preaching', 'It pleased God by the foolishness of preaching to save them that believe.', 'evangelist'),
      card('ev12', '1 Corinthians 9:16', 'Necessity laid upon me', 'For though I preach the gospel, I have nothing to glory of: for necessity is laid upon me; yea, woe is unto me, if I preach not the gospel!', 'evangelist'),
      card('ev13', '2 Corinthians 5:18', 'Ministry of reconciliation', 'And all things are of God, who hath reconciled us to himself by Jesus Christ, and hath given to us the ministry of reconciliation;', 'evangelist'),
      card('ev14', '2 Corinthians 5:20', 'Ambassadors for Christ', 'Now then we are ambassadors for Christ, as though God did beseech you by us...', 'evangelist'),
      card('ev15', 'Matthew 9:37', 'Harvest is plenteous', 'Then saith he unto his disciples, The harvest truly is plenteous, but the labourers are few;', 'evangelist'),
      card('ev16', 'Matthew 9:38', 'Pray for laborers', 'Pray ye therefore the Lord of the harvest, that he will send forth labourers into his harvest.', 'evangelist'),
      card('ev17', 'Acts 20:24', 'Finish my course', 'But none of these things move me, neither count I my life dear unto myself, so that I might finish my course with joy...', 'evangelist'),
      card('ev18', 'Colossians 1:28', 'Present every man', 'Whom we preach, warning every man, and teaching every man in all wisdom; that we may present every man perfect in Christ Jesus:', 'evangelist'),
      card('ev19', '1 Thessalonians 2:4', 'Approved by God', 'But as we were allowed of God to be put in trust with the gospel, even so we speak; not as pleasing men, but God...', 'evangelist'),
      card('ev20', 'James 5:20', 'Save a soul', 'Let him know, that he which converteth the sinner from the error of his way shall save a soul from death, and shall hide a multitude of sins.', 'evangelist'),
      card('ev21', 'Daniel 12:3', 'Turn many to righteousness', 'And they that be wise shall shine as the brightness of the firmament; and they that turn many to righteousness as the stars for ever and ever.', 'evangelist'),
    ],
  },
  {
    id: 'names-of-god',
    name: 'The Redemptive Name of God',
    description: 'Learn the powerful redemptive names of God and their meanings.',
    icon: '👑',
    color: '#7c3aed',
    unlockLevel: 5,
    cards: [
      card('ng1', 'Jehovah-Jireh', 'The Lord will provide', 'And Abraham called the name of that place Jehovahjireh: as it is said to this day, In the mount of the LORD it shall be seen. (Genesis 22:14)', 'names-of-god'),
      card('ng2', 'Jehovah-Rapha', 'The Lord that heals', 'For I am the LORD that healeth thee. (Exodus 15:26)', 'names-of-god'),
      card('ng3', 'Jehovah-Nissi', 'The Lord my banner', 'And Moses built an altar, and called the name of it Jehovahnissi. (Exodus 17:15)', 'names-of-god'),
      card('ng4', 'Jehovah-Shalom', 'The Lord our peace', 'Then Gideon built an altar there unto the LORD, and called it Jehovahshalom. (Judges 6:24)', 'names-of-god'),
      card('ng5', 'Jehovah-Raah', 'The Lord my shepherd', 'The LORD is my shepherd; I shall not want. (Psalm 23:1)', 'names-of-god'),
      card('ng6', 'Jehovah-Tsidkenu', 'The Lord our righteousness', 'And this is his name whereby he shall be called, THE LORD OUR RIGHTEOUSNESS. (Jeremiah 23:6)', 'names-of-god'),
      card('ng7', 'Jehovah-Mekoddishkem', 'The Lord who sanctifies', 'I am the LORD which sanctify you. (Leviticus 20:8)', 'names-of-god'),
      card('ng8', 'Jehovah-Sabaoth', 'The Lord of hosts', 'The LORD of hosts is with us; the God of Jacob is our refuge. Selah. (Psalm 46:7)', 'names-of-god'),
      card('ng9', 'Jehovah-Elyon', 'The Most High God', 'And he blessed him, and said, Blessed be Abram of the most high God, possessor of heaven and earth. (Genesis 14:19)', 'names-of-god'),
      card('ng10', 'Jehovah-El Olam', 'The Everlasting God', 'And Abraham planted a grove in Beersheba, and called there on the name of the LORD, the everlasting God. (Genesis 21:33)', 'names-of-god'),
      card('ng11', 'Jehovah-El Roi', 'The God who sees me', 'Thou God seest me. (Genesis 16:13)', 'names-of-god'),
      card('ng12', 'Jehovah-Gibbor', 'The Mighty God', 'The LORD is a man of war: the LORD is his name. (Exodus 15:3)', 'names-of-god'),
      card('ng13', 'Jehovah-Bore', 'The Lord our creator', 'Thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel. (Isaiah 43:1)', 'names-of-god'),
      card('ng14', 'Jehovah-Goel', 'The Lord our redeemer', 'Fear not, thou worm Jacob... saith the LORD, and thy redeemer, the Holy One of Israel. (Isaiah 41:14)', 'names-of-god'),
      card('ng15', 'Jehovah-Chereb', 'The Lord our sword', 'Thou shalt fear the LORD thy God... and shalt swear by his name. (Deuteronomy 6:13)', 'names-of-god'),
      card('ng16', 'Jehovah-Suri', 'The Lord my rock', 'The LORD is my rock, and my fortress, and my deliverer. (Psalm 18:2)', 'names-of-god'),
      card('ng17', 'Jehovah-Tsebaoth', 'Commander of armies', 'Holy, holy, holy, is the LORD of hosts: the whole earth is full of his glory. (Isaiah 6:3)', 'names-of-god'),
      card('ng18', 'Jehovah-Emeth', 'The Lord of truth', 'But the LORD is the true God, he is the living God, and an everlasting king. (Jeremiah 10:10)', 'names-of-god'),
      card('ng19', 'Jehovah-Hashophet', 'The Lord our judge', 'For the LORD is our judge, the LORD is our lawgiver, the LORD is our king; he will save us. (Isaiah 33:22)', 'names-of-god'),
      card('ng20', 'Jehovah-Magen', 'The Lord our shield', 'Fear not, Abram: I am thy shield, and thy exceeding great reward. (Genesis 15:1)', 'names-of-god'),
      card('ng21', 'Jehovah-Pele', 'The Lord who does wonders', 'He is wonderful in counsel, and excellent in working. (Isaiah 28:29)', 'names-of-god'),
    ],
  },

  // ── Level 7 ───────────────────────────────────────────────────────────
  {
    id: 'authority',
    name: 'The Authority to Cast Out Devils',
    description: 'Stand in the authority Christ has given believers over the enemy.',
    icon: '⚔️',
    color: '#ef4444',
    unlockLevel: 7,
    cards: [
      card('au1', 'Matthew 28:18', 'All authority given', 'And Jesus came and spake unto them, saying, All power is given unto me in heaven and in earth.', 'authority'),
      card('au2', 'Luke 9:1', 'Power over devils', 'Then he called his twelve disciples together, and gave them power and authority over all devils, and to cure diseases.', 'authority'),
      card('au3', 'Luke 10:17', 'Devils subject', 'And the seventy returned again with joy, saying, Lord, even the devils are subject unto us through thy name.', 'authority'),
      card('au4', 'Luke 10:19', 'Power over the enemy', 'Behold, I give unto you power to tread on serpents and scorpions, and over all the power of the enemy: and nothing shall by any means hurt you.', 'authority'),
      card('au5', 'Mark 16:17', 'Cast out devils', 'And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues;', 'authority'),
      card('au6', 'Matthew 10:1', 'Authority given', 'And when he had called unto him his twelve disciples, he gave them power against unclean spirits, to cast them out, and to heal all manner of sickness and all manner of disease.', 'authority'),
      card('au7', 'Matthew 12:28', 'Kingdom authority', 'But if I cast out devils by the Spirit of God, then the kingdom of God is come unto you.', 'authority'),
      card('au8', 'Mark 3:14', 'Sent with authority', 'And he ordained twelve, that they should be with him, and that he might send them forth to preach,', 'authority'),
      card('au9', 'Mark 3:15', 'Power to cast out', 'And to have power to heal sicknesses, and to cast out devils:', 'authority'),
      card('au10', 'Luke 4:36', 'Authority and power', 'And they were all amazed, and spake among themselves, saying, What a word is this! for with authority and power he commandeth the unclean spirits, and they come out.', 'authority'),
      card('au11', 'Acts 10:38', 'Oppressed of the devil', 'How God anointed Jesus of Nazareth with the Holy Ghost and with power: who went about doing good, and healing all that were oppressed of the devil; for God was with him.', 'authority'),
      card('au12', 'Acts 16:18', 'Commanded in Jesus\' name', 'And this did she many days. But Paul, being grieved, turned and said to the spirit, I command thee in the name of Jesus Christ to come out of her. And he came out the same hour.', 'authority'),
      card('au13', 'James 4:7', 'Resist the devil', 'Submit yourselves therefore to God. Resist the devil, and he will flee from you.', 'authority'),
      card('au14', 'Ephesians 6:12', 'Spiritual warfare', 'For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the darkness of this world, against spiritual wickedness in high places.', 'authority'),
      card('au15', 'Colossians 2:15', 'Powers disarmed', 'And having spoiled principalities and powers, he made a shew of them openly, triumphing over them in it.', 'authority'),
      card('au16', '1 John 3:8', 'Works of the devil destroyed', 'For this purpose the Son of God was manifested, that he might destroy the works of the devil.', 'authority'),
      card('au17', '1 John 4:4', 'Greater is He', 'Ye are of God, little children, and have overcome them: because greater is he that is in you, than he that is in the world.', 'authority'),
      card('au18', '2 Corinthians 10:4', 'Mighty through God', 'For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds;', 'authority'),
      card('au19', 'Luke 11:21', 'Strong man bound', 'When a strong man armed keepeth his palace, his goods are in peace:', 'authority'),
      card('au20', 'Luke 11:22', 'Stronger than he', 'But when a stronger than he shall come upon him, and overcome him, he taketh from him all his armour wherein he trusted, and divideth his spoils.', 'authority'),
      card('au21', 'Revelation 12:11', 'Overcome by testimony', 'And they overcame him by the blood of the Lamb, and by the word of their testimony; and they loved not their lives unto the death.', 'authority'),
    ],
  },
  {
    id: 'calling',
    name: 'The Call of God',
    description: 'Understand and answer the divine calling upon your life.',
    icon: '📯',
    color: '#0ea5e9',
    unlockLevel: 7,
    cards: [
      card('cl1', 'Matthew 22:14', 'Called and chosen', 'For many are called, but few are chosen.', 'calling'),
      card('cl2', 'Romans 8:30', 'Called according to purpose', 'Moreover whom he did predestinate, them he also called: and whom he called, them he also justified: and whom he justified, them he also glorified.', 'calling'),
      card('cl3', '2 Timothy 1:9', 'A holy calling', 'Who hath saved us, and called us with an holy calling, not according to our works, but according to his own purpose and grace.', 'calling'),
      card('cl4', '1 Corinthians 1:9', 'Called into fellowship', 'God is faithful, by whom ye were called unto the fellowship of his Son Jesus Christ our Lord.', 'calling'),
      card('cl5', 'Galatians 1:15', 'Called by grace', 'But when it pleased God, who separated me from my mother\'s womb, and called me by his grace.', 'calling'),
      card('cl6', 'Ephesians 4:1', 'Walk worthy of the call', 'Walk worthy of the vocation wherewith ye are called.', 'calling'),
      card('cl7', '1 Peter 2:9', 'Called out of darkness', 'Who hath called you out of darkness into his marvellous light.', 'calling'),
      card('cl8', 'Ephesians 1:4', 'Chosen before the foundation', 'According as he hath chosen us in him before the foundation of the world.', 'calling'),
      card('cl9', 'Colossians 3:12', 'The elect of God', 'Put on therefore, as the elect of God, holy and beloved.', 'calling'),
      card('cl10', 'Matthew 24:22', 'The elect preserved', 'But for the elect\'s sake those days shall be shortened.', 'calling'),
      card('cl11', 'John 15:16', 'Chosen and ordained', 'Ye have not chosen me, but I have chosen you, and ordained you.', 'calling'),
      card('cl12', 'Romans 11:29', 'Calling without repentance', 'For the gifts and calling of God are without repentance.', 'calling'),
      card('cl13', '2 Thessalonians 2:13', 'Chosen through the Spirit', 'God hath from the beginning chosen you to salvation through sanctification of the Spirit and belief of the truth.', 'calling'),
      card('cl14', 'Matthew 9:37-38', 'Harvest and laborers', 'The harvest truly is plenteous, but the labourers are few; Pray ye therefore the Lord of the harvest, that he will send forth labourers into his harvest.', 'calling'),
      card('cl15', 'Luke 10:2', 'Pray for laborers', 'The harvest truly is great, but the labourers are few: pray ye therefore the Lord of the harvest.', 'calling'),
      card('cl16', 'John 4:35', 'Fields ready to harvest', 'Lift up your eyes, and look on the fields; for they are white already to harvest.', 'calling'),
      card('cl17', 'Matthew 4:19', 'Called to follow', 'Follow me, and I will make you fishers of men.', 'calling'),
      card('cl18', '1 Thessalonians 5:24', 'God is faithful to the call', 'Faithful is he that calleth you, who also will do it.', 'calling'),
      card('cl19', 'Philippians 1:6', 'God completes the work', 'He which hath begun a good work in you will perform it until the day of Jesus Christ.', 'calling'),
      card('cl20', 'Hebrews 10:23', 'Faithful that promised', 'Let us hold fast the profession of our faith without wavering; for he is faithful that promised.', 'calling'),
      card('cl21', '1 Peter 5:10', 'Called unto eternal glory', 'The God of all grace, who hath called us unto his eternal glory by Christ Jesus.', 'calling'),
    ],
  },

  // ── Level 9 ───────────────────────────────────────────────────────────
  {
    id: 'name-of-jesus',
    name: 'Using the Name of Jesus',
    description: 'Wield the power and authority that is in the name of Jesus.',
    icon: '🌟',
    color: '#f97316',
    unlockLevel: 9,
    cards: [
      card('nj1', 'John 14:13', 'Ask in my name', 'And whatsoever ye shall ask in my name, that will I do, that the Father may be glorified in the Son.', 'name-of-jesus'),
      card('nj2', 'John 14:14', 'Promise of answered prayer', 'If ye shall ask any thing in my name, I will do it.', 'name-of-jesus'),
      card('nj3', 'John 15:16', 'Prayer connected to fruit', 'That whatsoever ye shall ask of the Father in my name, he may give it you.', 'name-of-jesus'),
      card('nj4', 'John 16:23', 'Direct access to the Father', 'Whatsoever ye shall ask the Father in my name, he will give it you.', 'name-of-jesus'),
      card('nj5', 'John 16:24', 'Fullness of joy', 'Ask, and ye shall receive, that your joy may be full.', 'name-of-jesus'),
      card('nj6', 'Acts 3:6', 'Healing in the name of Jesus', 'In the name of Jesus Christ of Nazareth rise up and walk.', 'name-of-jesus'),
      card('nj7', 'Acts 4:10', 'Power and salvation', 'By the name of Jesus Christ of Nazareth, whom ye crucified, whom God raised from the dead.', 'name-of-jesus'),
      card('nj8', 'Acts 4:12', 'Only name for salvation', 'Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.', 'name-of-jesus'),
      card('nj9', 'Acts 10:43', 'Remission of sins', 'Through his name whosoever believeth in him shall receive remission of sins.', 'name-of-jesus'),
      card('nj10', 'Acts 16:18', 'Authority over spirits', 'I command thee in the name of Jesus Christ to come out of her.', 'name-of-jesus'),
      card('nj11', 'Mark 16:17', 'Authority for believers', 'And these signs shall follow them that believe; In my name shall they cast out devils.', 'name-of-jesus'),
      card('nj12', 'Luke 10:17', 'Demons subject to his name', 'Even the devils are subject unto us through thy name.', 'name-of-jesus'),
      card('nj13', 'Matthew 18:20', 'Jesus present among believers', 'For where two or three are gathered together in my name, there am I in the midst of them.', 'name-of-jesus'),
      card('nj14', 'Colossians 3:17', 'All done in Jesus\' name', 'And whatsoever ye do in word or deed, do all in the name of the Lord Jesus.', 'name-of-jesus'),
      card('nj15', 'Philippians 2:9', 'Name above every name', 'God also hath highly exalted him, and given him a name which is above every name.', 'name-of-jesus'),
      card('nj16', 'Philippians 2:10', 'Universal authority', 'That at the name of Jesus every knee should bow.', 'name-of-jesus'),
      card('nj17', '1 Corinthians 6:11', 'Washed and sanctified', 'But ye are washed, but ye are sanctified, but ye are justified in the name of the Lord Jesus.', 'name-of-jesus'),
      card('nj18', 'Ephesians 5:20', 'Thanksgiving in his name', 'Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ.', 'name-of-jesus'),
      card('nj19', 'Hebrews 1:4', 'Excellent name', 'Being made so much better than the angels, as he hath by inheritance obtained a more excellent name than they.', 'name-of-jesus'),
      card('nj20', 'Romans 10:13', 'Calling on the name', 'For whosoever shall call upon the name of the Lord shall be saved.', 'name-of-jesus'),
      card('nj21', 'Acts 2:38', 'Baptized in Jesus\' name', 'Be baptized every one of you in the name of Jesus Christ for the remission of sins.', 'name-of-jesus'),
    ],
  },
  {
    id: 'prayer',
    name: 'Prayer',
    description: 'Draw near to God through the power of persistent prayer.',
    icon: '🙏',
    color: '#14b8a6',
    unlockLevel: 9,
    cards: [
      card('pr1', 'Jeremiah 33:3', 'God invites prayer', 'Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.', 'prayer'),
      card('pr2', 'Matthew 7:7', 'Ask, seek, knock', 'Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.', 'prayer'),
      card('pr3', 'Matthew 21:22', 'Prayer with faith', 'And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.', 'prayer'),
      card('pr4', 'Mark 11:24', 'Believe when you pray', 'What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.', 'prayer'),
      card('pr5', 'Luke 11:9', 'Persistence in prayer', 'Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.', 'prayer'),
      card('pr6', 'Luke 18:1', 'Do not faint in prayer', 'Men ought always to pray, and not to faint.', 'prayer'),
      card('pr7', 'John 14:13', 'Prayer glorifies God', 'Whatsoever ye shall ask in my name, that will I do, that the Father may be glorified in the Son.', 'prayer'),
      card('pr8', 'John 16:24', 'Joy through prayer', 'Ask, and ye shall receive, that your joy may be full.', 'prayer'),
      card('pr9', 'Romans 12:12', 'Continuing in prayer', 'Continuing instant in prayer.', 'prayer'),
      card('pr10', 'Philippians 4:6', 'Prayer replaces anxiety', 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.', 'prayer'),
      card('pr11', 'Colossians 4:2', 'Watchful prayer', 'Continue in prayer, and watch in the same with thanksgiving.', 'prayer'),
      card('pr12', '1 Thessalonians 5:17', 'Constant prayer', 'Pray without ceasing.', 'prayer'),
      card('pr13', '1 Timothy 2:1', 'Prayer for all people', 'Supplications, prayers, intercessions, and giving of thanks, be made for all men.', 'prayer'),
      card('pr14', 'Hebrews 4:16', 'Bold access to God', 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.', 'prayer'),
      card('pr15', 'James 1:5', 'Prayer for wisdom', 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally.', 'prayer'),
      card('pr16', 'James 5:16', 'Effectual prayer', 'The effectual fervent prayer of a righteous man availeth much.', 'prayer'),
      card('pr17', '1 John 5:14', 'Confidence in prayer', 'If we ask any thing according to his will, he heareth us.', 'prayer'),
      card('pr18', 'Psalm 34:17', 'God hears the righteous', 'The righteous cry, and the LORD heareth, and delivereth them out of all their troubles.', 'prayer'),
      card('pr19', 'Psalm 66:19', 'God attends to prayer', 'But verily God hath heard me; he hath attended to the voice of my prayer.', 'prayer'),
      card('pr20', 'Psalm 145:18', 'God near to those who pray', 'The LORD is nigh unto all them that call upon him, to all that call upon him in truth.', 'prayer'),
      card('pr21', 'Daniel 9:19', 'Earnest intercession', 'O Lord, hear; O Lord, forgive; O Lord, hearken and do; defer not, for thine own sake.', 'prayer'),
    ],
  },
];

export const allCards: ScriptureCard[] = decks.flatMap(d => d.cards);

export function getDeckById(id: string): Deck | undefined {
  return decks.find(d => d.id === id);
}

export function getCardById(id: string): ScriptureCard | undefined {
  return allCards.find(c => c.id === id);
}
